sct:
  db:
    address: 47.106.105.217:3306/scart_job_sit
    username: scart
    password: scart@2020
  redis:
    host: 47.106.105.217
    port: 9004
    password: Vigin123

spring:
  cloud:
    nacos:
      discovery:
        group: scart_sit_group