sct:
  db:
    address: 192.168.56.104:3306/scart_job_sit
    username: root
    password: Vigin123
  redis:
    host: 192.168.56.101
    port: 6379
    password: Vigin123

spring:
  cloud:
    nacos:
      discovery:
        group: scart_sit_group